// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountBottom: typeof import('./src/components/Account/AccountBottom.vue')['default']
    AccountHeader: typeof import('./src/components/Account/AccountHeader.vue')['default']
    Banner: typeof import('./src/components/Recommend/Banner.vue')['default']
    DetailBottom: typeof import('./src/components/Detail/DetailBottom.vue')['default']
    DetailHeader: typeof import('./src/components/Detail/DetailHeader.vue')['default']
    DetailTop: typeof import('./src/components/Detail/DetailTop.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ListPlayer: typeof import('./src/components/Player/ListPlayer.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    MiniPlayer: typeof import('./src/components/Player/MiniPlayer.vue')['default']
    NormalPlayer: typeof import('./src/components/Player/NormalPlayer.vue')['default']
    Personalized: typeof import('./src/components/Recommend/Personalized.vue')['default']
    PlayerBottom: typeof import('./src/components/Player/PlayerBottom.vue')['default']
    PlayerHeader: typeof import('./src/components/Player/PlayerHeader.vue')['default']
    PlayerMiddle: typeof import('./src/components/Player/PlayerMiddle.vue')['default']
    RelatedVideo: typeof import('./src/components/Video/RelatedVideo.vue')['default']
    ScrollView: typeof import('./src/components/ScrollView.vue')['default']
    SeeMoreItem: typeof import('./src/components/SeeMoreItem.vue')['default']
    SongList: typeof import('./src/components/Recommend/SongList.vue')['default']
    SongListItem: typeof import('./src/components/SongListItem.vue')['default']
    SonglistMore: typeof import('./src/components/SeeMore/SonglistMore.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    VideoDetail: typeof import('./src/components/Video/VideoDetail.vue')['default']
    VideoMore: typeof import('./src/components/SeeMore/VideoMore.vue')['default']
    Videoplayers: typeof import('./src/components/Video/Videoplayers.vue')['default']
  }
}

export { }
